name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erl_vsn: [21.3, 22.1, 23.0.3, 24.0]
    steps:
    - uses: actions/checkout@v2
    - uses: gleam-lang/setup-erlang@v1.1.0

      with:
        otp-version: ${{ matrix.erl_vsn }}

    - name: Setup DB
      run: make setup_db

    - name: Compile
      run: make compile

    - name: Check types
      run: make run_type_checks

    - name: Run tests
      run: make run_tests
