name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        erl_vsn: [21.1.8.1, 22.3.4.9, 23.3.4.5, 24.0.5]
    steps:
    - uses: actions/checkout@v2.0.0
    - uses: gleam-lang/setup-erlang@v1.1.2

      with:
        otp-version: ${{ matrix.erl_vsn }}

    - name: Setup DB
      run: make setup_db

    - name: Compile
      run: make compile

    - name: Check types
      run: make run_type_checks

    - name: Run tests
      run: make run_tests
